# Generated by Django 5.2.2 on 2025-06-10 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short description of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task.', null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='ongoing', help_text='Current status of the task.', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Due date for the task completion.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated.')),
                ('assignee', models.ForeignKey(blank=True, help_text='the user currently assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='The group this task belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.group')),
                ('owner', models.ForeignKey(help_text='the user who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
